language: go

go:
  - 1.15.x

env:
  - GO111MODULE=on

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.2
script: make lint test

notifications:
  email: false